// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void updateVideoImage(unsigned char* imageData, int imageWidth, int imageHeight);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_aa_2_png);   // assets/aa 2.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
