// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "esp_log.h"
#include "esp_heap_caps.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_Label2, -2 );
    lv_obj_set_y( ui_Label2, 114 );
    lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
    lv_label_set_text(ui_Label2,"Hello Paimon!");

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_aa_2_png);
    lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_Image2, 0 );
    lv_obj_set_y( ui_Image2, 0 );
    lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
    lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
    lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
}

void updateVideoImage(uint8_t*  imageData, int imageWidth, int imageHeight) {
    // Update the image source for ui_Image2 with the decoded image
    const lv_img_dsc_t img_buffer = {
        .header.cf = LV_IMG_CF_TRUE_COLOR,
        .header.always_zero = 0,
        .header.w = imageWidth,
        .header.h = imageHeight,
        .data_size = (size_t)(imageWidth * imageHeight * LV_COLOR_SIZE / 8),
        .data = (const uint8_t *)imageData,
    };

    // Update the image source for ui_Image2 to the new buffer
    lv_img_set_src(ui_Image2, &img_buffer);

    // Trigger a redraw of the image object
    lv_obj_invalidate(ui_Image2);
}


